### ISSUE TITLE
Model files for the training

### ISSUE THREAD

**Issue by Aditya-imerit** [Shk-aftab/Airborne-Detection-and-Tracking#1]
If possible, can you please upload the model files that has achieved accuracy of 0.955 mAP@0.5?

**Comment by Shk-aftab** [comment]
I have mailed you.

**Comment by kadirnar** [comment]
Hi @Shk-aftab @Aditya-imerit  

Can you share the model files for me too? 
Mail: kadir.nar@hotmail.com
Thanks.
